### ISSUE TITLE
Fundamentos de Ingenieria_U2_P1_Modelo de Negocio Nueva

### ISSUE THREAD

**Issue by KarlaV0** [SistemasTecTlaxiaco/practica-de-proceso-de-negocio-systems#1]
[Fundamentos de Ingenieria_U2_P1_Modelo de Negocio Nueva.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-proceso-de-negocio-systems/files/7368484/Fundamentos.de.Ingenieria_U2_P1_Modelo.de.Negocio.Nueva.pdf)

**Comment by Yabin-2021** [comment]
Anexo evaluación y calificación.
[Evaluación de reporte de practica BPMN.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-proceso-de-negocio-systems/files/7368809/Evaluacion.de.reporte.de.practica.BPMN.pdf)

**Calificación:
20 %**

**Comment by josealfredo79** [comment]
La propuesta de valor no esta bien definida.

**Comment by josealfredo79** [comment]
Se debe utilizar design thiking para asegurar...

**Comment by josealfredo79** [comment]
Bien hecho y revisado
